blank_issue_enabled: true
contact_links:
  - name: JagFX Dashboard Discord
    url: https://discord.gg/C4EEaHmPRs
    about: I hang around JagFX's Discord, so if you need assistance with any of the tools, feel free to join and ask!