name: Map Tile Upload
description: Fill out this form if you'd like to contribute to uploading tiles.
body:
- type: markdown
  attributes:
    value: |
      Thanks for wanting to contribute! Please fill out the form if you wish to upload tiles.
- type: dropdown
  id: game
  attributes:
    label: "Which game?"
    description: "Select which game you're providing tiles for."
    options:
      - ATS
      - ETS2
  validations:
    required: true
- type: input
  id: gver
  attributes:
    label: "What is your game version?"
    placeholder: Ex. v1.45
  validations:
    required: true
- type: dropdown
  id: promods
  attributes:
    label: "Is Promods being used?"
    description: "Select yes or no depending on if you use Promods."
    options:
      - "Yes"
      - "No"
  validations:
    required: true
- type: input
  id: pver
  attributes:
    label: "What is your Promods version?"
    placeholder: Ex. v2.01
- type: textarea
  id: uplink
  attributes:
    label: "Link to Map Tiles"
    description: |
      Link to the map tiles you'd like to contribute.
  validations:
    required: true
- type: checkboxes
  id: tested
  attributes:
    label: "Have the tiles been tested?"
    description: |
      It is *required* that you test the map tiles first before contributing.
      If you have tested them, and read the [CONTRIBUTING](CONTRIBUTE.md)
- type: textarea
  id: add
  attributes:
    label: "Additional Information"
    description: |
      If you have anything else to add, feel free to add it here.
      This will include any particular map mods that either add onto Promods, or are different to the base game.